"use client";
import { FaBolt, FaFire, FaHeartbeat, FaWalking } from "react-icons/fa";
import { Area, AreaChart, ResponsiveContainer, Tooltip, XAxis, YAxis } from "recharts";
import { PageHeader } from "@/components/layout/page-header";
import { StatCard } from "@/components/dashboard/stat-card";
import { weeklyActivity, workouts } from "@/lib/mock-data";
import { Button } from "@/components/ui/button";

export default function DashboardPage() {
  return <><PageHeader title="Your fitness overview" description="Small actions, consistently done, create the biggest change." action={<Button>Start today&apos;s workout</Button>} /><section className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4"><StatCard label="Calories burned" value="2,840" trend="↑ 12% from last week" icon={FaFire} /><StatCard label="Active minutes" value="316 min" trend="↑ 48 min this week" icon={FaBolt} tone="sky" /><StatCard label="Steps today" value="8,429" trend="84% of daily target" icon={FaWalking} tone="violet" /><StatCard label="Recovery score" value="86 / 100" trend="Excellent readiness" icon={FaHeartbeat} tone="orange" /></section><section className="mt-6 grid gap-6 xl:grid-cols-[1.6fr_1fr]"><article className="panel min-h-[330px] p-6"><div className="mb-6"><p className="font-bold">Weekly activity</p><p className="text-sm text-slate-500">Calories burned across your training week</p></div><ResponsiveContainer width="100%" height={240}><AreaChart data={weeklyActivity}><defs><linearGradient id="calories" x1="0" x2="0" y1="0" y2="1"><stop offset="0%" stopColor="#10b981" stopOpacity={0.35} /><stop offset="100%" stopColor="#10b981" stopOpacity={0} /></linearGradient></defs><XAxis dataKey="day" axisLine={false} tickLine={false} /><YAxis hide /><Tooltip /><Area type="monotone" dataKey="calories" stroke="#10b981" strokeWidth={3} fill="url(#calories)" /></AreaChart></ResponsiveContainer></article><article className="panel p-6"><p className="font-bold">Today&apos;s focus</p><p className="mt-1 text-sm text-slate-500">Keep your streak moving.</p><div className="mt-6 rounded-2xl bg-gradient-to-br from-emerald-500 to-sky-500 p-5 text-white"><p className="text-sm font-semibold text-white/80">Next session</p><p className="mt-1 text-xl font-bold">Upper Body Strength</p><p className="mt-4 text-sm">45 minutes · Intermediate</p><Button variant="secondary" className="mt-5 w-full">View workout</Button></div></article></section><section className="mt-6"><h2 className="mb-4 text-xl font-bold">Recommended for you</h2><div className="grid gap-4 md:grid-cols-3">{workouts.map((workout) => <article key={workout.title} className="panel overflow-hidden"><div className={`h-2 bg-gradient-to-r ${workout.color}`} /><div className="p-5"><p className="font-bold">{workout.title}</p><p className="mt-1 text-sm text-slate-500">{workout.focus}</p><div className="mt-4 flex justify-between text-xs font-semibold"><span>{workout.duration}</span><span className="text-emerald-600">{workout.level}</span></div></div></article>)}</div></section></>;
}
