"use client";
import { useState } from "react";
import { FaBell, FaShieldAlt } from "react-icons/fa";
import { PageHeader } from "@/components/layout/page-header";
import { Button } from "@/components/ui/button";
import { useAppStore } from "@/store/app-store";

function Toggle({ checked, onChange }: { checked: boolean; onChange: () => void }) { return <button type="button" onClick={onChange} className={`relative h-7 w-12 rounded-full transition ${checked ? "bg-emerald-500" : "bg-slate-300 dark:bg-slate-700"}`}><span className={`absolute top-1 h-5 w-5 rounded-full bg-white transition ${checked ? "left-6" : "left-1"}`} /></button>; }
export default function SettingsPage() { const [notifications, setNotifications] = useState(true); const [weekly, setWeekly] = useState(true); const addToast = useAppStore((state) => state.addToast); return <><PageHeader title="Settings" description="Choose how AIFit Coach supports your routine." /><div className="grid max-w-3xl gap-6"><section className="panel p-6"><div className="flex items-center gap-3"><FaBell className="text-emerald-500" /><div><h2 className="font-bold">Notifications</h2><p className="text-sm text-slate-500">Stay on top of the moments that matter.</p></div></div><div className="mt-6 grid gap-5"><div className="flex items-center justify-between"><div><p className="font-medium">Workout reminders</p><p className="text-sm text-slate-500">A nudge before your planned session.</p></div><Toggle checked={notifications} onChange={() => setNotifications(!notifications)} /></div><div className="flex items-center justify-between"><div><p className="font-medium">Weekly progress summary</p><p className="text-sm text-slate-500">Your wins, patterns and next focus.</p></div><Toggle checked={weekly} onChange={() => setWeekly(!weekly)} /></div></div></section><section className="panel p-6"><div className="flex items-center gap-3"><FaShieldAlt className="text-sky-500" /><div><h2 className="font-bold">Privacy</h2><p className="text-sm text-slate-500">Your health data stays under your control.</p></div></div><Button variant="outline" className="mt-6" onClick={() => addToast({ title: "Data export queued", description: "A demo notification only—nothing was exported." })}>Request data export</Button></section></div></> }
